apiVersion: v1
kind: Service

metadata:
  name: shipping-service-svc
  namespace: logistic-shipping-prod

spec:
  selector:
    app: shipping-service

  type: ClusterIP

  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP